// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sijbjijvgxgjgkbvwhte.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpamJqaWp2Z3hnamdrYnZ3aHRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NjQyODIsImV4cCI6MjA4ODA0MDI4Mn0.2M-zG3aFZAPgi-h32ZLN8xbVJP8F0R6ohUAGKS74xG4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});